{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.ljt",
    "module": "btservice",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btservice-1.0.aar",
          "url": "btservice-1.0.aar",
          "size": 316795,
          "sha512": "a5c2c71984755100bb4d5e0173f0806fba15a6df175772f14d9069722cf4a98a4fe0cc3960a0b67fdb77ff88b041bb0826b16afeeee91e4546a3661ad09233ae",
          "sha256": "5f78be42d8504951de675fca161fc980373ce5fbc08eb4061421abe8a53ec33a",
          "sha1": "c8cb7499bdc96507a65f2ac59fcdf1c759ae6449",
          "md5": "6ac60677d230d9ff6c4a1cb00aa26c01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "btservice-1.0.aar",
          "url": "btservice-1.0.aar",
          "size": 316795,
          "sha512": "a5c2c71984755100bb4d5e0173f0806fba15a6df175772f14d9069722cf4a98a4fe0cc3960a0b67fdb77ff88b041bb0826b16afeeee91e4546a3661ad09233ae",
          "sha256": "5f78be42d8504951de675fca161fc980373ce5fbc08eb4061421abe8a53ec33a",
          "sha1": "c8cb7499bdc96507a65f2ac59fcdf1c759ae6449",
          "md5": "6ac60677d230d9ff6c4a1cb00aa26c01"
        }
      ]
    }
  ]
}
