{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.ljt",
    "module": "btservice",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btservice-1.0.aar",
          "url": "btservice-1.0.aar",
          "size": 317176,
          "sha512": "43a5a98263dd47c9b5b5b32e069a4fe90a8df1ac1e114750c840e033a976b0bbdde42d6f6671b3903dc2af29b5a5d7d79c3c73b1b53bc1e6d2b590b59456f5ee",
          "sha256": "fd16649472e4a7f6da7eeed29019256c5476aa1d034fa7b85abc83f68d77252e",
          "sha1": "a4672397a444708f6f155033ec5d2f48a482e151",
          "md5": "f2a6180e0bd25795ff4cb27b5134b817"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "btservice-1.0.aar",
          "url": "btservice-1.0.aar",
          "size": 317176,
          "sha512": "43a5a98263dd47c9b5b5b32e069a4fe90a8df1ac1e114750c840e033a976b0bbdde42d6f6671b3903dc2af29b5a5d7d79c3c73b1b53bc1e6d2b590b59456f5ee",
          "sha256": "fd16649472e4a7f6da7eeed29019256c5476aa1d034fa7b85abc83f68d77252e",
          "sha1": "a4672397a444708f6f155033ec5d2f48a482e151",
          "md5": "f2a6180e0bd25795ff4cb27b5134b817"
        }
      ]
    }
  ]
}
