{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.ljt",
    "module": "btservice",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btservice-1.0.aar",
          "url": "btservice-1.0.aar",
          "size": 316713,
          "sha512": "162d05544195f1a007a8c6097301feb9f569d28f252c4a23fa698314b23d8a4239155d8b4dd8c6722f1f48ed2c7b6e49a7b4f68138133d77899a6f475ac0060c",
          "sha256": "cc644b8a9310ba2b55197148de1c45324ce5b72839c6d05d2c8562983ae94caf",
          "sha1": "51a5172b498fb47a1a919750c146a03d4033d84d",
          "md5": "0fb33122875db9c14549c1c1ec5b6ba2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "btservice-1.0.aar",
          "url": "btservice-1.0.aar",
          "size": 316713,
          "sha512": "162d05544195f1a007a8c6097301feb9f569d28f252c4a23fa698314b23d8a4239155d8b4dd8c6722f1f48ed2c7b6e49a7b4f68138133d77899a6f475ac0060c",
          "sha256": "cc644b8a9310ba2b55197148de1c45324ce5b72839c6d05d2c8562983ae94caf",
          "sha1": "51a5172b498fb47a1a919750c146a03d4033d84d",
          "md5": "0fb33122875db9c14549c1c1ec5b6ba2"
        }
      ]
    }
  ]
}
