{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tti.kiosk",
    "module": "keyboard",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "keyboard-1.3.aar",
          "url": "keyboard-1.3.aar",
          "size": 180928,
          "sha512": "69bc1bc782936c5b71fd654ddaedb90338d12e0dad0d8c1df9f00ad46b2d9d2d23423a7a85640abcca2c9b6b13d54ac0adcb55b61dd3b3b336845c16e2d98369",
          "sha256": "93e52cf6497d6ce28c5a8b397c5509f0b12eac35aa693bb8b9f46a1ba8613ceb",
          "sha1": "de0f44a05387330fb85fb686e821d1a7c8a2a1aa",
          "md5": "388dd0c8023c2a16cfd061b58f95394e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keyboard-1.3.aar",
          "url": "keyboard-1.3.aar",
          "size": 180928,
          "sha512": "69bc1bc782936c5b71fd654ddaedb90338d12e0dad0d8c1df9f00ad46b2d9d2d23423a7a85640abcca2c9b6b13d54ac0adcb55b61dd3b3b336845c16e2d98369",
          "sha256": "93e52cf6497d6ce28c5a8b397c5509f0b12eac35aa693bb8b9f46a1ba8613ceb",
          "sha1": "de0f44a05387330fb85fb686e821d1a7c8a2a1aa",
          "md5": "388dd0c8023c2a16cfd061b58f95394e"
        }
      ]
    }
  ]
}
